WIP: circle invoice payment split
thematters/matters-server pull request #1742
Opened 2021-01-26 17:00 UTC by Carolusian

2021-02-01 07:33 UTC, robertu7 requested changes
Left some comments, others look good to me.

2021-02-01 07:33 UTC, robertu7 commented on db/migrations/20210119152027_create_circle_invoice_table.js
> +    t.bigInteger('user_id').unsigned().notNullable
`.notNullable()`?

2021-02-01 07:33 UTC, robertu7 commented on src/connectors/paymentService.ts
> +            `currency for '${providerTxId}' if not the same to '${p.providerPriceId}'`
typo? `if` -> `is`?

2021-02-01 07:33 UTC, robertu7 commented on src/routes/pay/stripe.ts
> +        provider: PAYMENT_PROVIDER.stripe,
missing `archived: false`?

2021-02-01 07:33 UTC, robertu7 commented on src/routes/pay/stripe.ts
> +    const tx = (await paymentService.findTransactions({ providerTxId }))[0]
Same as below, save some DB costs if return first (`if (!tx) { return }`)?

2021-02-01 08:48 UTC, devformatters requested changes
Left one comment.

2021-02-01 08:48 UTC, devformatters commented on src/connectors/paymentService.ts
> +        const circle = await this.atomService.findFirst({
I would not recommend to init atomService in another service. You can get rid of `atomService` by using:
- `this.baseFindById`  (paymentService extends baseService)
- `this.knex().select().where().first()`

2021-02-02 00:35 UTC, guoliu approved these changes
Looks good, let's try it 🍀

2021-02-02 06:09 UTC, robertu7 approved these changes

2021-02-02 06:09 UTC, robertu7 commented on src/connectors/paymentService.ts
> +        const circle = await this.baseFindById(p.circleId.toString(), 'circle')
`.toString()` is unnecessary, i beleve.

2021-02-02 13:58 UTC, Carolusian commented on db/migrations/20210119152027_create_circle_invoice_table.js
> +    t.bigInteger('user_id').unsigned().notNullable
updated.

2021-02-03 03:18 UTC, devformatters approved these changes
Go. 🦊

2021-02-03 04:07 UTC, merged