WIP: Add APIs of circle invitation
thematters/matters-server pull request #1852
Opened 2021-03-18 06:51 UTC by devformatters

2021-03-18 08:11 UTC, jeremyOk approved these changes

2021-03-18 09:03 UTC, robertu7 requested changes

2021-03-18 10:18 UTC, devformatters commented on db/migrations/20210315152127_create_circle_invitation_table.js
> +    t.index(['inviter', 'circle_id'])
Nice point.

2021-03-18 10:18 UTC, devformatters commented on src/mutations/circle/invite.ts
> +      where: { circleId: circle.id, email, userId },
Added. Thx.

2021-03-18 10:18 UTC, devformatters commented on src/mutations/circle/invite.ts
> +    where: { id: circleId },
Fixed.

2021-03-19 03:23 UTC, robertu7 approved these changes
🥼

2021-03-19 03:34 UTC, merged