feat(article): add `revision_count` to article table
thematters/matters-server pull request #1920
Opened 2021-04-14 08:03 UTC by robertu7

2021-04-14 09:42 UTC, devformatters requested changes

2021-04-14 09:42 UTC, devformatters commented on db/migrations/20210414144806_add_article_revision_count.js
> +        publish_state = 'published'
include `pending` ?

2021-04-15 02:32 UTC, guoliu approved these changes

2021-04-15 02:53 UTC, devformatters approved these changes
Go. 👕

2021-04-15 03:00 UTC, merged