feat(search): deprecate SearchInput.version and SearchInput.version, …
thematters/matters-server pull request #3333
Opened 2023-05-05 09:35 UTC by gary02

…remove old version search code

2023-05-05 12:57 UTC, robertu7 requested changes

2023-05-05 12:57 UTC, robertu7 commented on src/types/system.ts
>      version: SearchAPIVersion
can use `@deprecated` directive?

2023-05-09 15:10 UTC, gary02 commented on src/types/system.ts
>      version: SearchAPIVersion
https://matterslab.slack.com/archives/C88CK7Q7L/p1669339562477699

2023-05-09 15:55 UTC, robertu7 approved these changes

2023-05-09 15:55 UTC, robertu7 approved these changes

2023-05-12 09:06 UTC, merged